substitutions:
  devicename: esp-pac
  long_devicename: PAC

esphome:
  name: $devicename
  comment: $long_devicename
  platform: esp8266
  board: esp01_1m

# Décodage des commandes : https://github.com/m000c400/Mitsubishi-CN105-Protocol-Decode
# https://github.com/tobias-93/esphome-ecodan-heatpump  => - source: github://tobias-93/esphome-ecodan-heatpump@main
external_components:
  - source: github://Desperado88/esphome-ecodan-heatpump@main
    components: [ ecodan ]

logger:
  baud_rate: 0

api:

ota:
  - platform: esphome
    password: "*****************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.14
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-01S-Pac Fallback Hotspot"
    password: "T3mAc7QQBRzs"

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  id: ecodan_uart
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3
  rx_buffer_size: 1024
  parity: EVEN

ecodan:
  id: ecodan_instance
  uart_id: ecodan_uart

text_sensor:
  - platform: version
    name: $devicename ESPHome Version
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    ssid:
      name: $devicename SSID
    bssid:
      name: $devicename BSSID
  - platform: ecodan
    date_time:
      name: $devicename Actuelle date/time
    defrost:
      name: $devicename Décongélation
    heating_stage:
      name: $devicename Étape de chauffe
    operating_mode:
      name: $devicename Mode de fonctionnement
    heat_cool:
      name: $devicename Chauffage/refroidissement
    hot_water_timer:
      name: $devicename Minuterie d'eau chaude
    date_energy_cons:
      name: $devicename Date de consommation d'énergie
    date_energy_prod:
      name: $devicename Production d'énergie à partir de dattes      
    holiday_mode:
      name: $devicename Mode vacances
    # zone2_room_temp:
    #   name: $devicename Zone 2 Room Temperature
    # zone2_flow_temp:
    #   name: $devicename Zone 2 Flow Temperature


sensor:
  - platform: uptime
    name: $devicename Uptime
  - platform: wifi_signal
    name: $devicename WiFi Signal
    update_interval: 60s
  - platform: ecodan
    error_code:
      name: $devicename Code d'erreur
    frequency:
      name: $devicename Fréquence
    output_power:
      name: $devicename Puissance de sortie
    zone1_room_temperature:
      name: $devicename Zone 1 Room Temperature
    # zone1_flow_temp_setpoint:
    #   name: $devicename Zone 1 Flow Temperature Setpoint
    # zone2_room_temperature:
    #   name: $devicename Zone 2 Room Temperature
    # zone2_flow_temp_setpoint:
    #   name: $devicename Zone 2 Flow Temperature Setpoint
    gas_return_temp_signed:
      name: $devicename Température de retour du gaz
    outside_temperature:
      name: $devicename Température extérieure
    water_feed_temp_signed:
      name: $devicename Température d'alimentation en eau
    water_return_temp_signed:
      name: $devicename Température de retour d'eau
    hot_water_temperature:
      name: $devicename Température de l'eau chaude
    runtime:
      name: $devicename Durée d'exécution
    water_flow:
      name: $devicename Débit d'eau
    energy_cons_yesterday:
      name: $devicename Consommation d'énergie de chauffage (hier)
    energy_prod_yesterday:
      name: $devicename Production d'énergie de chauffage (hier)
    energy_cooling_cons_yesterday:
      name: $devicename Consommation d'énergie de refroidissement (hier)
    energy_cooling_prod_yesterday:
      name: $devicename Production d'énergie de refroidissement (hier)
    energy_dhw_cons_yesterday:
      name: $devicename Consommation d'énergie pour l'eau chaude (hier)
    energy_dhw_prod_yesterday:
      name: $devicename Production d'énergie pour l'eau chaude (hier)

switch:
  - platform: ecodan
    power_state:
      name: $devicename État de l'alimentation
    force_dhw:
      name: $devicename Force DHW

select:
  - platform: ecodan
    mode_select:
      name: $devicename Mode
    hot_water_mode:
      name: $devicename Mode eau chaude

number:
  - platform: ecodan
    hot_water_setpoint:
      name: $devicename Point de consigne de l'eau chaude
    zone1_room_temp_setpoint:
      name: $devicename Consigne de température ambiante
    zone1_flow_temp_setpoint:
      name: $devicename Consigne de température de départ
    # zone2_room_temp_setpoint:
    #   name: $devicename Zone 2 Room Temperature Setpoint
    # zone2_flow_temp_setpoint:
    #   name: $devicename Zone 2 Flow Temperature Setpoint